name: Build AMD only mesa-git

on:
  push:
    paths:
      - '.github/workflows/amd-mesa.yml'
      - '.github/workflows/PKGBUILD'
  workflow_dispatch:

jobs:
  build-and-package-mesa:
    runs-on: ubuntu-latest

    container:
      image: archlinux:base

    steps:
    - name: Update system and install build dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm git base-devel

    - name: Clone repo for PKGBUILD
      run: |
         git clone https://github.com/buildingpkgs/mg.git

    - name: Build Mesa
      run: |
        sed -i 's/^#MAKEFLAGS/MAKEFLAGS/' /etc/makepkg.conf
        useradd user -mG wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        chown user -R .
        cd mg/.github/workflows
        su user -c "yes|PKGDEST=/tmp/mesa-git makepkg --noconfirm -s"

    - name: Create artifact
      uses: actions/upload-artifact@v4
      with:
        name: mesa-amd
        path: |
            /tmp/mesa-git/*.zst
            
