name: Build and package Mesa Git

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-package-mesa-git:
    runs-on: ubuntu-latest

    container:
      image: archlinux:base

    steps:
    - name: Update system and install build dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm git base-devel

    - name: Clone Mesa Git repository
      run: git clone https://aur.archlinux.org/mesa-git.git

    - name: Build Mesa Git
      run: |
        useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        chown user -R .
        cd mesa-git
        su user -c makepkg -s --noconfirm

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: mesa-git-package
        path: mesa-git/pkg/
