name: Build mesa-git
on:
  push:
    paths:
      - '.github/workflows/main.yml'
  workflow_dispatch:
jobs:
  build-and-package-mesa-git:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base
    steps:
    - name: Update system and install build dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm git base-devel mesa
    - name: Clone Mesa and directx-headers and llvm-minimal-git and spirv-tools and spirv-headers
      run: |
        git clone https://aur.archlinux.org/mesa-git.git
        git clone https://aur.archlinux.org/directx-headers-git.git
        git clone https://aur.archlinux.org/llvm-minimal-git.git
        git clone https://aur.archlinux.org/spirv-headers-git.git
        git clone https://aur.archlinux.org/spirv-tools-git.git
    - name: Build Mesa and directx-headers
      run: |
        useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        chown user -R .
        su user -c "sed -i 's/^#MAKEFLAGS/MAKEFLAGS/' /etc/makepkg.conf"

        cd directx-headers-git
        su user -c "makepkg -si --noconfirm"
        cd ..
        cd mesa-git
        su user -c "makepkg -s --noconfirm"
    - name: Create artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: mesa-devel
        path: mesa-git/*zst



